name: fz_theme
description: Theme system for FromZero UI.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.3.1
  flutter_font_icons: ^3.0.0
  bitsdojo_window: ^0.1.6
  hive_flutter: ^1.1.0
  intl: ^0.20.2

  fz_app_update:
    path: ../fz_app_update
  fz_combo:
    path: ../fz_combo
  fz_tooltip:
    path: ../fz_tooltip
  fz_scaffold:
    path: ../fz_scaffold
  fz_ui_utility:
    path: ../fz_ui_utility
  fz_localizations:
    path: ../fz_localizations

dev_dependencies:
  flutter_lints: ^5.0.0
