name: fz_expansion_tile
description: Expansion tile widget (copied and customized from Flutter).
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_font_icons: ^3.0.0

  fz_actions:
    path: ../fz_actions
  fz_copy_ensure_visible:
    path: ../fz_copy_ensure_visible
  fz_drawer_menu:
    path: ../fz_drawer_menu
  fz_future_handling:
    path: ../fz_future_handling
  fz_translucent_ink_well:
    path: ../fz_translucent_ink_well
  fz_ui_utility:
    path: ../fz_ui_utility
  fz_popup:
    path: ../fz_popup

dev_dependencies:
  flutter_lints: ^5.0.0
