name: fz_animated_widgets
description: Implicitly animated versions of Flutter widgets that are missing animated variants.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
