name: fz_file_saver
description: File saver utility for FromZero UI.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

  dartx: ^1.2.0
  device_info_plus: ^11.4.0
  dio: ^5.8.0+1
  humanizer: ^3.0.0
  intl: ^0.20.2
  open_filex: ^4.7.0
  pasteboard: ^0.4.0
  path: ^1.8.0
  permission_handler: ^12.0.0+1
  sanitize_filename: ^1.0.5
  universal_html: ^2.2.3
  url_launcher: 6.3.1

  fz_api_handling:
    path: ../fz_api_handling
  fz_localizations:
    path: ../fz_localizations
  fz_log:
    path: ../fz_log
  fz_platform:
    path: ../fz_platform
  fz_snackbar:
    path: ../fz_snackbar

dev_dependencies:
  flutter_lints: ^5.0.0
