name: fz_dao
description: Data Access Objects and form fields for FromZero UI.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.3.1
  flutter_font_icons: ^3.0.0
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  dartx: ^1.2.0
  dio: ^5.8.0+1
  email_validator: ^3.0.0
  intl: ^0.20.2
  multi_value_listenable_builder: ^0.0.2
  sliver_tools: ^0.2.12
  preload_page_view: ^0.2.0
  path: ^1.8.0

  fz_animations:
    path: ../fz_animations
  fz_api_handling:
    path: ../fz_api_handling
  fz_combo:
    path: ../fz_combo
  fz_comparable_list:
    path: ../fz_comparable_list
  fz_copy_ensure_visible:
    path: ../fz_copy_ensure_visible
  fz_tooltip:
    path: ../fz_tooltip
  fz_dialog:
    path: ../fz_dialog
  fz_file_picker:
    path: ../fz_file_picker
  fz_future_handling:
    path: ../fz_future_handling
  fz_focus_traversal:
    path: ../fz_focus_traversal
  fz_localizations:
    path: ../fz_localizations
  fz_platform:
    path: ../fz_platform
  fz_snackbar:
    path: ../fz_snackbar
  fz_ui_utility:
    path: ../fz_ui_utility
  fz_value_string:
    path: ../fz_value_string
  fz_actions:
    path: ../fz_actions
  fz_scaffold:
    path: ../fz_scaffold
  fz_scrollbar:
    path: ../fz_scrollbar
  fz_appbar:
    path: ../fz_appbar
  fz_table:
    path: ../fz_table
  fz_translucent_ink_well:
    path: ../fz_translucent_ink_well
  fz_selectable_icon:
    path: ../fz_selectable_icon
  fz_date_picker:
    path: ../fz_date_picker
  fz_popup:
    path: ../fz_popup
  fz_opacity_gradient:
    path: ../fz_opacity_gradient
  fz_log:
    path: ../fz_log

dev_dependencies:
  flutter_lints: ^5.0.0
