name: fz_scrollbar
description: Custom scrollbar with scroll controller for FromZero UI.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

  fz_bitsdojo_window:
    path: ../fz_bitsdojo_window
  fz_platform:
    path: ../fz_platform
  fz_opacity_gradient:
    path: ../fz_opacity_gradient

dev_dependencies:
  flutter_lints: ^5.0.0
